[build]
  functions = "functions"
  publish = "public"

[[headers]]
  for = "/script.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/style.css"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidat
